on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+

name: Berkeley DB 4.8 APKs

jobs:
  v3_13:
    name: v3.13
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          mkdir -p keys
          echo "${{ secrets.BUILDER_RSA }}" > keys/builder.rsa
          echo "${{ secrets.BUILDER_RSA_PUB }}" }} > keys/builder.rsa.pub
          make -C v3.13/v4.8.30 build
      -
        uses: actions/upload-artifact@v2
        with:
          name: bdv-3.13
          path: v3.13/v4.8.30/packages/x86_64
